### ISSUE TITLE
how to generate a new address ?

### ISSUE THREAD

**Issue by cgeek** [XDagger/xdag#117]
how to generate a new address ?

**Comment by xrdavies** [comment]
@cgeek 

If you are using wallet, not possible right now. But later this feature will be added.

**Comment by mathsw** [comment]
CLI keygen command should generate a new address and set it as default.

**Comment by judezhu** [comment]
@xrdavies I generated an account using the windows wallet gui. What do you mean by not possible now? Thanks.

**Comment by xrdavies** [comment]
@mathsw keygen will generate a new key, but not working with wallet. With pool, yes.

**Comment by forest21000** [comment]
@xrdavies Agree with you!We can create a new address by copying the wallet program to another folder,and input one pool address to get new address.

**Comment by xrdavies** [comment]
Close.
