### ISSUE TITLE
cann't pass compile  /xdag/client

### ISSUE THREAD

**Issue by kaocs** [XDagger/xdag#118]
to compile client  in  Ubuntu 4.13    gcc 4.8.5   

Error INFO As Below:
pool.c:929:21: error: dereferencing pointer to incomplete type ‘struct hostent’
   if (!host || !host->h_addr_list[0]) {
                     ^
pool.c:933:10: error: ‘h_errno’ undeclared (first use in this function)
    res = h_errno;
          ^
pool.c:933:10: note: each undeclared identifier is reported only once for each function it appears in
sha256.c: In function ‘sha256_final’:
sha256.c:140:3: warning: implicit declaration of function ‘memset’ [-Wimplicit-function-declaration]
   memset(cdata, 0, 56);
   ^
sha256.c:140:3: warning: incompatible implicit declaration of built-in function ‘memset’
sha256.c:140:3: note: include ‘<string.h>’ or provide a declaration of ‘memset’
../dnet/dnet_threads.c: In function ‘dnet_thread_work’:
../dnet/dnet_threads.c:77:10: warning: implicit declaration of function ‘gethostbyname’ [-Wimplicit-function-declaration]
   host = gethostbyname(str);
          ^
../dnet/dnet_threads.c:77:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   host = gethostbyname(str);
        ^
../dnet/dnet_threads.c:78:21: error: dereferencing pointer to incomplete type ‘struct hostent’
   if (!host || !host->h_addr_list[0]) {
                     ^
../dnet/dnet_threads.c:79:54: error: ‘h_errno’ undeclared (first use in this function)
    mess = "cannot resolve host ", mess1 = str; res = h_errno;
                                                      ^
../dnet/dnet_threads.c:79:54: note: each undeclared identifier is reported only once for each function it appears in
Makefile:97: recipe for target 'xdag' failed
make: *** [xdag] Error 1

**Comment by xrdavies** [comment]
@kaocs 
Could you specify which branch used?

**Comment by kaocs** [comment]
master develop Pre_release  are all these Errors.

**Comment by xrdavies** [comment]
@ljxu  @kaocs Did you use make or automake?

**Comment by jonano614** [comment]
@kaocs did you manage to compile the project?
