### ISSUE TITLE
Can not connect to the main network.

### ISSUE THREAD

**Issue by zywoo** [XDagger/xdag#123]
ubuntu 16.04.
run ./xdag with -d  -p and -P parameters. 
It always "Trying to connect to the main network". 
![image](https://user-images.githubusercontent.com/12759228/39804762-8a08dbd4-53a7-11e8-8ebb-88ec9df543f6.png)

**Comment by xrdavies** [comment]
@zywoo @RyanKung  All the pools closed the port for mining to sync the main net.

Close this issue.
