### ISSUE TITLE
how do my pool IP update to whitelist?

### ISSUE THREAD

**Issue by SkyblueMr** [XDagger/xdag#124]
I'm start xdag daemon:
./xdag -d -r -p 47.75.1.95:16775 -P 47.75.1.95:12315:2048:0.5:1:1:200:1
thanks!

**Comment by SkyblueMr** [comment]
This is IP and Pool Server in Hong Kong, so the Great Firewall of China can't interfere with block synchronization.
please

**Comment by mathsw** [comment]
Please be patient. Once that the network is stable, more pools will slowly be added.

**Comment by SkyblueMr** [comment]
Thx very much.

**Comment by xrdavies** [comment]
@SkyblueMr 

Please pay attention the news on http://xdag.io and follow the routine to add white-list.
