### ISSUE TITLE
What's happening to XDAG from 7/5/2018？

### ISSUE THREAD

**Issue by NKU-Nikoni** [XDagger/xdag#125]
XDAG is in great discussion these days, but no one could explain exactly what happened.
We are eager to know what caused this accident.
XDAG community, tell something, please.

**Comment by zz546141724** [comment]
@mathsw ok thanks

**Comment by mathsw** [comment]
@NKU-Nikoni https://xdag.io/2018/05/09/Report-on-Desynchronization-of-Network.html

**Comment by NKU-Nikoni** [comment]
@mathsw  thanks a lot
