### ISSUE TITLE
The balance in wallet is cleared to 0.010631004 XDAG when my PC is powered off accidentally and powered it back

### ISSUE THREAD

**Issue by huangfaqian** [XDagger/xdag#136]
My question: How can I repair my wallet? Thanks.

**Comment by jonano614** [comment]
Hi, did the address of your wallet was changed?

**Comment by cnukaus** [comment]
@huangfaqian probably invalid chain due to de-sync?

**Comment by xrdavies** [comment]
No updates for over two months. Closed.
