### ISSUE TITLE
Help, a problem with a wallet.

### ISSUE THREAD

**Issue by zarenkovanton** [XDagger/xdag#160]
Hello. How to restore a wallet. After restart of a wallet, it hangs on initialization?

**Comment by xrdavies** [comment]
@zarenkovanton 

Could you provide more info?

**Comment by sgaragagghu** [comment]
@zarenkovanton check the password

**Comment by zarenkovanton** [comment]
@sgaragagghu Thanks, it likely validly a problem with the password because writes me the following mistake to the console:
C:\Users\wallet\Downloads\XDag.x64\XDag.x64\xdag.exe -p 172.105.216.53:3355 -d
xdag client/server, version 0.2.1.
Transport module: dnet T11.231-T13.714.
Password:
Password incorrect.

It is necessary only to understand what password and why the fact that I entered doesn't approach...

@xrdavies Whether there are any mechanisms on recovery of the password? I from 100% know the password, but in the console it doesn't approach.

**Comment by sgaragagghu** [comment]
maybe you typed the password with CAPS LOCK ?
try to simulate the errors that you could have done while typing it the first time.

**Comment by zarenkovanton** [comment]
I have already tried, even in the native language. I have tried to pass letters and to enter other letter which I could enter by mistake. password of 14 symbols.

**Comment by xrdavies** [comment]
No updates over 3 months. Close.
