### ISSUE TITLE
Cannot connect the main network.

### ISSUE THREAD

**Issue by BravoJason** [XDagger/xdag#163]
Hi, I want to start my own pool.

When I followed the tutorial of the https://github.com/XDagger/openxdagpool-scripts, it can not connect the main network.

Here is the start command: 
`pool@ip-172-31-34-249:~/xdag1/client$ TZ=GMT ./xdag -d -p 54.164.118.71:16775 -P 54.164.118.71:13654:20000:2000:450:1:1:1:1`

Here is the state prompt:
```
xdag> state
Trying to connect to the main network.
```

Here is the stats prompt:
```
xdag> stats
Statistics for ours and maximum known parameters:
            hosts: 34 of 34
           blocks: 7 of 7
      main blocks: 5 of 5
    orphan blocks: 1
 wait sync blocks: 0
 chain difficulty: 000000057d75e6383 of 000000057d75e6383
      XDAG supply: 5120.000000000 of 5120.000000000
4 hr hashrate MHs: 0.00 of 0.00
```
Connection state:
```
xdag> net conn
Current connections:
xdag> net hosts
Active hosts:
  0. 6274700E                   0 sec, T13.714, local     trust  127.0.0.1:0
xdag> net host
6274700E                   0 sec, T13.714, trust
```

Could you tell me is there any configuration problem for my code?

Thanks for your time.

**Comment by mathsw** [comment]
Hello @BravoJason 

Please read about the requirements and process here:
https://github.com/XDagger/xdag/wiki/White-List

**Comment by leruy** [comment]
@BravoJason If there is no other pool to add you to the white list, you are not connected to the main network.

**Comment by BravoJason** [comment]
Ok. I see. It means that I should be added first and then sync the blocks. Thank you.

**Comment by xrdavies** [comment]
@BravoJason 

If you wanna run your pool, you have to apply for white-list to pool@xdag.io. The requirement is listed in https://github.com/XDagger/xdag/wiki/White-List
If you wanna run test pool by your own, please setup your test net by yourself.
