### ISSUE TITLE
xdag was MIT licensed, is now GPL licensed; action needed

### ISSUE THREAD

**Issue by trueserve** [XDagger/xdag#181]
Commit 1a88c7cbc5be9565a06986b154dd60ab396e15fa has merged in support for Readline.

This project is MIT licensed. However, Readline is GPL. Binaries built with this software, and distribution of this software in source or binary form, must comply with the GPL license. This is more restrictive than the MIT license. Because of these restrictoins, this commit should be immediately reverted.

Any unrelated fixes should be recommited per task without being merged into a single commit.

An alternate method for command history or completion should be devised.

**Comment by xrdavies** [comment]
@trueserve 

Fixed in https://github.com/XDagger/xdag/pull/186
