### ISSUE TITLE
full audit of the discord moderation group

### ISSUE THREAD

**Issue by rgsnedds** [XDagger/xdag#182]
As pool support for https://xdag.signal2noi.se

why have i been removed from the chat??
I would advise a full audit of the discord moderation group.

thank you for your time.

Rus

**Comment by trueserve** [comment]
You were permanently banned, by me, after being unbanned at least twice from prior bans for the same reasons listed below, on May 20th 2018.

The `#rules-info` channel in Discord lists the following rules:
```
Rules
1.  No referral links.
2. No advertising.
3. No impersonation.
4. No personal information unless it is made publicly available by the person themselves.
5. Be respectful.
6. Post in the correct channel. 
7. No punishment evasion.
```
The largest rule infracted was rule 5. As a community we are pretty open and tolerant. Your abuse of this rule was allowed to slip for some time. As the instigations, namecalling and outright disrespect were amplified, you were asked to stop. When you did not stop and began instigating in response to this question, you were banned, and then permanently banned when you came back and did the same thing.

It has come to my attention that you were on the server as an alt, violating rule 7, and were banned by moderator @mathsw.

For posterity, you had another rude message relayed to me by another member after this ban. I am not certain why you want to be a part of this community when these are the actions you take.

This audit has been completed, and this ticket will be closed.
