### ISSUE TITLE
xdag can't run on centos

### ISSUE THREAD

**Issue by yurocy** [XDagger/xdag#22]
➜  client git:(develop) ✗ ./xdag -m 2 -d 172.105.216.53:3355
xdag client/server, version 0.2.0.Transport module: dnet T11.231-T13.714, running as daemon.
Password: 
➜  client git:(develop) ✗ ./xdag -i
xdag client/server, version 0.2.0.
xdag> help
Can't connect to unix domain socket errno:2
xdag>

**Comment by xrdavies** [comment]
@yurocy 
Could you check if you have unix_sock.dat in that folder?

**Comment by yurocy** [comment]
@xrdavies no, can't find it

**Comment by xrdavies** [comment]
@yurocy 
On Linux, the unix_sock.dat is used for communication between xdag deamon and terminal, if no unix_sock.dat, it will throw the error as you met. So please update to the latest version and re-run daemon like ./xdag -m 2 -d 172.105.216.53:3355, then run terminal in the same folder like ./xdag -i

**Comment by xrdavies** [comment]
@yurocy  Still now unix_sock.dat created?

**Comment by xrdavies** [comment]
@yurocy 
If no such issue any more, we will suppose this issue is not existed and close this issue.

**Comment by aidenluo177** [comment]
@xrdavies There is not unix_sock.dat file on my server(CentOS 6.8)

**Comment by xrdavies** [comment]
@aidenluo177 Please check the command to run xdag
./xdag -d -m 2 the.pool.address:port

then run ./xdag -i

**Comment by ljxu** [comment]
where can i get the.pool.address

**Comment by xrdavies** [comment]
@ljxu  Pool address are listed in [wiki](https://github.com/XDagger/xdag/wiki/Mineable-Pool-List) and https://xdag.io

**Comment by xrdavies** [comment]
It's not issue anymore. With new version has better compatibility with BSD like system.
