### ISSUE TITLE
rpc xdag_new_address error

### ISSUE THREAD

**Issue by okfirelee** [XDagger/xdag#256]
array(1) { [0]=> array(1) { ["block"]=> string(32) "4Q8CT7iZ3The6HzUTAgMufI9PAYDMm1V" } } err 2 result errno:-32601 msg: Method not found. array(0) { }

**Comment by okfirelee** [comment]
method not found?  why ? its not complicate?

**Comment by mathsw** [comment]
RPC is not finished yet. Please wait some time for full RPC release.
