### ISSUE TITLE
account 100 is only 67 address

### ISSUE THREAD

**Issue by okfirelee** [XDagger/xdag#258]
i use xdag -i
account 100
only create 67 address . is not 100.  and account 200 only 67 . 
i need more address how to do?

**Comment by sgaragagghu** [comment]
account 100 doesn't create new addresses, you shouldn't use these other addresses that you see because some of these addresses are transaction addresses, not wallet addresses.

**Comment by okfirelee** [comment]
how to create new wallet addresses ? i want build user pay functions need more address

**Comment by xrdavies** [comment]
@okfirelee  Not possible to create multiple addresses with wallet not. Please try transaction remark in 0.3.1.
