### ISSUE TITLE
issue cheato2xdag for display

### ISSUE THREAD

**Issue by xrdavies** [XDagger/xdag#309]
https://explorer.xdag.io/block/oKw26wfTgKAsPJ5yXNB4f1g5VN8ZVUU6

所有input相加值为71.359999927；output值却是71.359999932，input竟然还＜output

**Comment by sgaragagghu** [comment]
How he did xfer of 0.0000 ? It should be disabled by wallet and in pool payment

**Comment by xrdavies** [comment]
@sgaragagghu  It should be history issue I think. The old version still handle cheatos less than 4 which will be displayed as 0 xdag.

**Comment by xrdavies** [comment]
Not an issue with new versions.
