### ISSUE TITLE
issue with network when there are more than 25 IPs

### ISSUE THREAD

**Issue by xrdavies** [XDagger/xdag#318]
As reported from Pool owner that when one pool has connections from over 25 IPs, this pool will be in desynced status, and the network hash rate will drop a lot.

**Comment by sgaragagghu** [comment]
It should be already fixed with new dnet and #262

**Comment by xrdavies** [comment]
@sgaragagghu  Anyone test with this fix?

**Comment by xrdavies** [comment]
Verified with 0.3.0 on pool.xdag.us:13654
