### ISSUE TITLE
pool configuration has no effect.

### ISSUE THREAD

**Issue by xrdavies** [XDagger/xdag#37]
Reported from pools guy, the pool cannot change the configuration 
![297e041059de470ba4d9e8f7a391ff9f](https://user-images.githubusercontent.com/1884084/37865516-80d9e7dc-2fb8-11e8-8367-3326ed0a3331.jpg)

**Comment by xrdavies** [comment]
Please compile this on your server, run it and paste the result here.


```
#include <stdio.h>
#include <unistd.h>

#define ONE_MB (1024 * 1024)

int main()
{
    printf("The number of processors configured is :%ld\n",
        sysconf(_SC_NPROCESSORS_CONF));
    printf("The number of processors currently online (available) is :%ld\n",
        sysconf(_SC_NPROCESSORS_ONLN));
    printf ("The pagesize: %ld\n", sysconf(_SC_PAGESIZE));  
    printf ("The number of pages: %ld\n", sysconf(_SC_PHYS_PAGES));  
    printf ("The number of available pages: %ld\n", sysconf(_SC_AVPHYS_PAGES)); 
    printf ("The memory size: %lld MB\n", 
        (long long)sysconf(_SC_PAGESIZE) * (long long)sysconf(_SC_PHYS_PAGES) / ONE_MB );  
    printf ("The number of files max opened:: %ld\n", sysconf(_SC_OPEN_MAX));  
    printf("The number of ticks per second: %ld\n", sysconf(_SC_CLK_TCK));  
    printf ("The max length of host name: %ld\n", sysconf(_SC_HOST_NAME_MAX));  
    printf ("The max length of login name: %ld\n", sysconf(_SC_LOGIN_NAME_MAX)); 
    return 0;
}
```

**Comment by xrdavies** [comment]
`The number of processors configured is :8
The number of processors currently online (available) is :8
The pagesize: 4096
The number of pages: 3849791
The number of available pages: 51076
The memory size: 15038 MB
The number of files max opened:: 65535
The number of ticks per second: 100
The max length of host name: 64
The max length of login name: 256`

Result pasted.

**Comment by czsilence** [comment]
`ulimit -a`
see your system limit, 960 may be caused by open file max is 1024

and use "ulimit -n xxx" to set open file max limit. eg:

`
ulimit -n 4096
`

**Comment by xrdavies** [comment]
@czsilence 
As I mentioned in previous reply, there is little code to check max open file. It's quite weird that the max open file is 65535 while in xdag it seems still 1024. Unable to reproduce with my pool. Need the pool guy contact me again.

**Comment by xrdavies** [comment]
@czsilence Could you continue the investigation?

**Comment by xrdavies** [comment]
no updates for over 3 months. Closed.
