### ISSUE TITLE
miner disconnect abnormal

### ISSUE THREAD

**Issue by xrdavies** [XDagger/xdag#412]
Pool version: 0.3.0

Platform: centos

Description:

Miners are disconnected by Success! It's abnormal!

Below is the log info:

```Pool: miner XX...XXX disconnected from 172.31.10.13:31116 by read error : Success```

**Comment by sgaragagghu** [comment]
`On success, the number of bytes read is returned (zero indicates end of file)`
so it seems issue on miner side, maybe we should change the message in the case data read is 0 
because technically it is not an error :joy:

**Comment by xrdavies** [comment]
Fixed in #414
