### ISSUE TITLE
Add one 2 more spaces to "net conn" listing after IP and port

### ISSUE THREAD

**Issue by kbs1** [XDagger/xdag#438]
Otherwise lines like this might get printed on really long-lasting pool connections (now happening in production):
```
5. 195.201.169.202:177773595780 sec, 86183834624/466876300288 in/out bytes, 168327802/911867774 packets, 3042085/0 dropped
```
As you can see, the port is glued together with number of seconds. This can't be parsed as it is ambiguos in many cases. Not a big issue, but such lines are ignored by openxdagpool-scripts and xdag-explorer (incorrect number of elements when line is exploded by \s+), and therefore are not present in status JSON API outputs such as https://explorer.xdag.io/api/status or http://xdagger.corpopool.com/status

**Comment by xrdavies** [comment]
solved.
