### ISSUE TITLE
install make error log

### ISSUE THREAD

**Issue by okfirelee** [XDagger/xdag#453]
In file included from src/secp256k1.c:17:0,
                 from src/tests.c:17:
src/ecmult_const_impl.h: In function ‘secp256k1_wnaf_const’:
src/ecmult_const_impl.h:113:20: warning: ‘u’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     wnaf[word] = u * global_sign;
                    ^
  CCLD     tests
  CC       src/exhaustive_tests-tests_exhaustive.o
  CCLD     exhaustive_tests
make[1]: Leaving directory `/home/xdag/xdag2/xdag/secp256k1'
cc -o xdag secp256k1.o -isystem../secp256k1/include/ -lgmp address.c block.c crypt.c hash.c init.c main.c memory.c netdb.c pool.c miner.c mining_common.c sha256.c storage.c sync.c transport.c wallet.c commands.c terminal.c network.c time.c math.c ../dnet/dnet_crypt.c ../dnet/dnet_xdag.c ../dus/programs/dfstools/source/dfslib/dfslib_crypt.c ../dus/programs/dfstools/source/dfslib/dfslib_random.c ../dus/programs/dfstools/source/dfslib/dfslib_string.c ../dus/programs/dfstools/source/lib/dfsrsa.c ../dus/programs/dar/source/lib/crc_c.c ./utils/utils.c ./utils/log.c ./utils/linenoise.c ./utils/dirname.c ./utils/moving_statistics/moving_average.c ./json-rpc/cJSON.c ./json-rpc/cJSON_Utils.c ./json-rpc/rpc_procedure.c ./json-rpc/rpc_procedures.c ./json-rpc/rpc_service.c ./json-rpc/rpc_wrapper.c ./json-rpc/rpc_commands.c ./http/url.c ./http/http.c  sha256-mb-x86_64.s x86_64cpuid.s -DSHA256_USE_OPENSSL_TXFM -DSHA256_OPENSSL_MBLOCK -I.. -I./utils -std=gnu11 -O3 -DDFSTOOLS -DCHEATCOIN -DNDEBUG -g -lpthread -lcrypto -lssl -lm -Wall -Wmissing-prototypes -Wno-unused-result -Wl,--export-dynamic
In file included from block.c:29:0:
utils/atomic.h:69:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
In file included from pool.c:36:0:
utils/atomic.h:69:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
miner.c: In function ‘xdag_pick_pool’:
miner.c:414:2: warning: missing braces around initializer [-Wmissing-braces]
  char addresses[30][50] = {0};
  ^
miner.c:414:2: warning: (near initialization for ‘addresses[0]’) [-Wmissing-braces]
In file included from transport.c:18:0:
utils/atomic.h:69:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
make: *** [xdag] Error 1

**Comment by xrdavies** [comment]
Please upgrade your gcc version to 4.9+. It's bug of gcc.

**Comment by reymondtu** [comment]
see #504

**Comment by xrdavies** [comment]
Gcc version requirement already addressed in wiki [https://github.com/XDagger/xdag/wiki/Getting-started](https://github.com/XDagger/xdag/wiki/Getting-started)
