### ISSUE TITLE
Error when building from the source for linux(CentOS)

### ISSUE THREAD

**Issue by tonyYOLO** [XDagger/xdag#454]
[root@izt4nf41cvya1mzsrupx5pz ~]# cd xdag/client
[root@izt4nf41cvya1mzsrupx5pz client]# make
\033[0;31mPlease install libgmp-dev to have better performance\033[0m
cd ../secp256k1 && ./autogen.sh && ./configure && make;                                       \
cd ../client && cc -O3 -DHAVE_CONFIG_H -I../secp256k1/src/ -I../secp256k1 -c ../secp256k1/src/secp256k1.c 
./autogen.sh:行3: autoreconf: 未找到命令
In file included from ../secp256k1/src/secp256k1.c:11:0:
../secp256k1/src/util.h:11:33: 致命错误：libsecp256k1-config.h：没有那个文件或目录
 #include "libsecp256k1-config.h"
                                 ^
编译中断。
make: *** [secp256k1] 错误 1

**Comment by xrdavies** [comment]
Please follow the instructions.
https://github.com/XDagger/xdag/wiki/Getting-started

**Comment by wangxuguo** [comment]
@xrdavies 
when compile by automake:
make  all-am
make[1]: Entering directory '/home/wxg/xdag_space/xdag/automake'
gcc -DHAVE_CONFIG_H -I.    -std=gnu11 -O3 -g -DDFSTOOLS -DCHEATCOIN -DNDEBUG -DSHA256_USE_OPENSSL_TXFM -DSHA256_OPENSSL_MBLOCK -I/usr/local/opt/openssl/include -I.. -I../dnet -I../dus/programs/dfstools/source/dfslib -I../dus/programs/dfstools/source/include -I../dus/programs/dar/source -I../ldus/source/include/ldus -I../client/utils -I../client/utils/moving_statistics -I../client/json-rpc -I../client/http -I../secp256k1/src -I../secp256k1/                                  -Wall -Wmissing-prototypes -Wno-unused-result -g -O2 -c -o ../secp256k1/src/xdag-secp256k1.o `test -f '../secp256k1/src/secp256k1.c' || echo './'`../secp256k1/src/secp256k1.c
In file included from ../secp256k1/src/secp256k1.c:11:0:
../secp256k1/src/util.h:11:10: fatal error: libsecp256k1-config.h: No such file or directory
 #include "libsecp256k1-config.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:913: recipe for target '../secp256k1/src/xdag-secp256k1.o' failed
make[1]: *** [../secp256k1/src/xdag-secp256k1.o] Error 1
make[1]: Leaving directory '/home/wxg/xdag_space/xdag/automake'
Makefile:473: recipe for target 'all' failed
make: *** [all] Error 2


@xrdavies  when compile secp256k1,by ./autogen.sh 
Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:3:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

**Comment by xrdavies** [comment]
@sgaragagghu  Could you add it to wiki page Getting Started?

**Comment by xrdavies** [comment]
The steps are addressed in wiki [https://github.com/XDagger/xdag/wiki/Getting-started](https://github.com/XDagger/xdag/wiki/Getting-started)
