### ISSUE TITLE
mac connection to website fails

### ISSUE THREAD

**Issue by cnukaus** [XDagger/xdag#49]
Mac connection to website https fail, httpse OK
![screen_shot_2018-03-27_at_12 50 24_pm](https://user-images.githubusercontent.com/5101195/37950039-e1521be4-31e2-11e8-9f9f-2b4bb2764781.png)

**Comment by xrdavies** [comment]
@cnukaus 
It seems an issue about ssl certification. 

Move to xdag.io repository.
