### ISSUE TITLE
Remove mining from wallet

### ISSUE THREAD

**Issue by xdgruben** [XDagger/xdag#5]
Is not necessary anymore, since we already have a cpu/gpu miner.

**Comment by sgaragagghu** [comment]
I think cpu miner of the gpu miner isn't optimized

**Comment by jonano614** [comment]
Mister @sgaragagghu is right. CPU miner is not optimized. Need more coding

**Comment by Sofarlemineur** [comment]
we have a CPU miner only?

**Comment by cnukaus** [comment]
Shall we make this a switch? I can potentially work on this (haven't wrote C for many years) or ask a buddy of mine to work on this

**Comment by xrdavies** [comment]
@Sofarlemineur 
Please find the GPU Miner https://github.com/XDagger/DaggerGpuMiner

**Comment by felixwqliu** [comment]
@jonano614 CPU miner maybe write using ASM，to optimiz it

**Comment by jonano614** [comment]
@felixwqliu the CPU-mining was already optimized in January. Now it makes no sense to try to optimize it more....

**Comment by xrdavies** [comment]
No need, close it.
