### ISSUE TITLE
Error building from the source for Linux

### ISSUE THREAD

**Issue by bergstar** [XDagger/xdag#514]
Unable to build from current master on Ubuntu 18.10

```
In file included from ../secp256k1/src/secp256k1.c:11:
../secp256k1/src/util.h:11:10: fatal error: libsecp256k1-config.h: No such file or directory
 #include "libsecp256k1-config.h"

```

Using 
```
  autoreconf -if
  ./configure 
  make
```

Also did try to install the dev package `sudo apt install libsecp256k1-dev` - same error.

**Comment by wangxuguo** [comment]
You can try:
      ./secp256k1/autogen.sh

**Comment by wangxuguo** [comment]
Sorry, You should run ./configure in secp256k1  after  ./autogen.sh; then make in automake.Fully is like this below,

cd secp256k1
./autogen.sh
./configure 
cd ..
cd automake
 autoreconf -if
  ./configure 
  make

**Comment by wangxuguo** [comment]
if sth is wrong. you may try make in client

**Comment by xrdavies** [comment]
Address the solution in wiki [https://github.com/XDagger/xdag/wiki/Getting-started](https://github.com/XDagger/xdag/wiki/Getting-started)
