### ISSUE TITLE
Add "version" command to xdag -i

### ISSUE THREAD

**Issue by kbs1** [XDagger/xdag#551]
Currently multiple pieces of software need to check running xdag version. It is currently not possible without running `xdag --help` and parsing out the version.

Proposed is the following new command: `version`. It should just print version, e.g. `0.3.1`. In addition to that, a command line option `-v` should be implemented that will allow to check XDAG version without printing full `--help` argument.

**Comment by xrdavies** [comment]
fixed in #552
