### ISSUE TITLE
Unable to run $make on Ubuntu

### ISSUE THREAD

**Issue by cestvictor** [XDagger/xdag#584]
Hi,
Here is the erro after running the commamd $make. Could help me with this?
![image](https://user-images.githubusercontent.com/21105519/113942820-66a9ff80-97f9-11eb-8a28-48fd2dad3d45.png)

**Comment by swordlet** [comment]
it seemed that randomx library is not installed.
you may compile and install randomx library from source https://github.com/tevador/RandomX
or install binary using command :   apt-get install librandomx-dev

**Comment by MyronX** [comment]
you can try to  use cmake to build the project

```
sudo apt-get install git  cmake gcc  libssl-dev libgmp-dev libtool libsecp256k1-dev   librandomx-dev  pkg-config
mkdir build && cd  build
cmake ..
make
```
u can start ./xdag in build

**Comment by swordlet** [comment]
there is a binary release in
https://github.com/XDagger/XdagRandomxMiner/releases/tag/v0.4

**Comment by cestvictor** [comment]
Thanks all, the binary program works.
