### ISSUE TITLE
linux build issues

### ISSUE THREAD

**Issue by rgsnedds** [XDagger/xdag#7]
GPU's show correct hash-rate in terminal, but pools only seeing  a small percentage of hash-rate and rewards not paying correctly, tested on multiple pools over the course of many hours (8 hrs overnight)

**Comment by xrdavies** [comment]
@jonano614 
Do you think it's an issue of pool or GPU miner?

**Comment by rgsnedds** [comment]
well it only happened on ethos.
it’s not a huge issue but i think it the miner.

there are other small things with the miner, like sometimes the need to run seperate instances for each card etc.

however, there is obviously some issues with pools. our first pool would disconnect every 48hrs, so we have moved to another server. it has been two weeks now and we are just almost sync!

overall it just looks like minor bugs in all parts of the software.

**Comment by xrdavies** [comment]
@rgsnedds 

Thanks for reply.
Not sure if your IP of pool is added to white-list or not.
Please check current white-list.

And if it's a miner issue, I will move it to GPU miner and close this one.

**Comment by rgsnedds** [comment]
Hi,

Yes our pool is in the whitelist.
We have spent the past two weeks ensuring that the pool is connecting. It connects OK and loads blocks from local storage, but when the local blocks are loaded, it begins again from zero and loads again.
It’s almost fully loaded now so hopefully we will be running soon


R

**Comment by xrdavies** [comment]
It's unrelated to linux build. Close.
