### ISSUE TITLE
xdag-cli last command

### ISSUE THREAD

**Issue by 2ge** [XDagger/xdag#82]
Hi,

it would be convenient if we could bring last commands on arrow up, same like in bash:

```
xdag> account
[address]          0.000000000  key 0
xdag> ^[[A
Illegal command.
```

using xdag on OSX. Thank you

**Comment by reymondtu** [comment]
xdag-cli need command history features, this is not bug

**Comment by xrdavies** [comment]
Currently it's not in plan of 0.2.2. We will consider this feature in later releases. Thank you for information!
