### ISSUE TITLE
Dagger info paper

### ISSUE THREAD

**Issue by 2ge** [XDagger/xdag#83]
Hi guys,

I am preparing XDAG info paper, so I can spread this information. Please peer review it, let me know what should be changed/added/deleted. After we can put it here as WIKI page and post it to community, so all useful info will be on one place.

Thanks

https://docs.google.com/document/d/1b8OmK4RPGtMkh4qQyaLYVQM-Lfym1gKqR1Hq3Rrf7oM/edit?usp=sharing

**Comment by mathsw** [comment]
Please create a .md for easy formatting for the wiki. 

See https://guides.github.com/features/mastering-markdown/ for info.
