### ISSUE TITLE
openxdagpool-scripts setup error: there is not cheatcoin folder and xdag_run.sh

### ISSUE THREAD

**Issue by tihualong** [XDagger/xdag#9]
> Once all is done, go to templates directory in this repository, and COPY all files to both `xdag1/cheatcoin` and `xdag2/cheatcoin`. Edit the `xdag_run.sh` file in both folders with *your* pool settings.
Re-execute xdag1 using `./xdag_run.sh` in `xdag1/cheatcoin` folder without the `-r` option (script will ask). Wait for the pool to start up and load blocks from the storage.

in openxdagpool-scripts>readme file , there is not cheatcoin folder and xdag_run.sh 。

**Comment by jonano614** [comment]
cheatcoin folder was renamed to client
