### ISSUE TITLE
How can I update whitelist, if I want to add a xdag miner pool?

### ISSUE THREAD

**Issue by luch-jinming** [XDagger/xdag#95]

**Comment by luch-jinming** [comment]
Could help me add  pool 106.14.95.35:13654 in whitelist

**Comment by luch-jinming** [comment]
I append netdb-white.txt `106.14.95.35:13654`, and start xdag daemon  `./xdag -d -p 106.14.95.35:16775 -P 106.14.95.35:13654:20000:0.5:1:1:200:0.5`.  Is it all right?

**Comment by xrdavies** [comment]
@luch-jinming 
The IP address should be accept by other pool owners. Please submit PR to add your pool.

**Comment by luch-jinming** [comment]
@xrdavies Tks!  I have submitted a PR.
